apiVersion: v1
kind: Secret
metadata:
  name: mysecret
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "helmakskubernetespoc-chart.labels" . | nindent 4 }}
type: Opaque
stringData:
    ConnectionStrings.DefaultConnection: __ConnectionStrings.DefaultConnection__