apiVersion: v1
kind: Secret
metadata:
  name: mysecret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
    ConnectionStrings.DefaultConnection: __ConnectionStrings.DefaultConnection__