apiVersion: v1
kind: Service
metadata:
  name: {{ include "helmakskubernetespoc-chart.fullname" .}}
  labels:
    {{- include "helmakskubernetespoc-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "helmakskubernetespoc-chart.selectorLabels" . | nindent 4 }}

kind: Service
apiVersion: v1
metadata:
  name: {{ include "helmakskubernetespoc-chart.fullname" .}}external
  namespace: default
    labels:
      {{- include "helmakskubernetespoc-chart.labels" . | nindent 4 }}
spec:
  type: ExternalName
  externalName: {{ include "helmakskubernetespoc-chart.fullname" .}}.{{ .Release.Namespace }}.svc.cluster.local
  ports:
  - port: 80