apiVersion: v1
kind: Service
metadata:
  name: {{ include "helmakskubernetespoc-chart.fullname" .}}{{.Release.Namespace }}
  labels:
    {{- include "helmakskubernetespoc-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "helmakskubernetespoc-chart.selectorLabels" . | nindent 4 }}
