name: 1.1$(rev:.r) # build numbering format

trigger: none # will disable CI builds entirely

variables:
  BuildConfiguration: "Release"
  PublishPath: $(Build.Repository.LocalPath)/Pipelines/Building/DockerContent # used in Dockerfile
  CsProjectPath: "Sources/Application/*.csproj"

resources:
  pipelines:
    - pipeline: HAKP-ci-pip # Name of the pipeline resource
      source: 01-HAKP-Continuous-Integration # Name of the pipeline referenced by the pipeline resource
      trigger:
        branches:
          - refs/heads/master
jobs:
  - job: "BuildAndCreateImages"
    displayName: "Build and create Images"
    pool:
      vmImage: "ubuntu-20.04"
    steps:
      - task: qetza.replacetokens.replacetokens-task.replacetokens@5
        displayName: "Replace tokens in **/*.yaml"
        inputs:
          rootDirectory: "$(Build.SourcesDirectory)"
          targetFiles: |
            **/*.json
            **/*.yaml
          tokenPattern: rm
          verbosity: detailed
          keepToken: true
      - task: DotNetCoreCLI@2
        displayName: Publish
        inputs:
          command: publish
          publishWebProjects: false
          projects: $(CsProjectPath)
          arguments: "--configuration $(BuildConfiguration) --output $(PublishPath) /p:DeleteExistingFiles=True"
          zipAfterPublish: false
          modifyOutputPath: false
      - task: YodLabs.VariableTasks.SetVariable.SetVariable@0
        displayName: "Set Variable ImageName to $(Build.Repository.Name) with toLowerCase applied"
        inputs:
          variableName: ImageName
          value: "$(Build.Repository.Name)"
          transform: toLowerCase
      - task: YodLabs.VariableTasks.SetVariable.SetVariable@0
        displayName: "Set Variable ImageName to $(ImageName) with replace applied"
        inputs:
          variableName: ImageName
          value: "$(ImageName)"
          transform: replace
          searchValue: '\.'
          newValue: "-"
      - task: Docker@0
        displayName: "Build Docker Image"
        inputs:
          buildContext: "Tra"
          containerregistrytype: "Container Registry"
          dockerRegistryConnection: DockerHub
          imageName: "$(ImageName)"
          additionalImageTags: "$(Build.BuildNumber)"
          includeLatestTag: true
          Dockerfile: Pipelines/Building/Dockerfile
      - task: Docker@0
        displayName: "Push Docker Image"
        inputs:
          containerregistrytype: "Container Registry"
          dockerRegistryConnection: DockerHub
          action: "Push an image"
          imageName: "$(ImageName)"
          additionalImageTags: "$(Build.BuildNumber)"
          includeLatestTag: true
      - task: PublishBuildArtifacts@1
        displayName: "Publish"
        inputs:
          PathtoPublish: "Pipelines/Releasing"
