name: 1.0$(rev:.r) # build numbering format

variables:
  BuildConfiguration: 'Release'
  ApplyDockerstack: false
  FolderToPublish: 'Application'
  PublishPath: $(Build.Repository.LocalPath)/DockerContent
  
resources:
  repositories:
  - repository: ALMStuff
    type: github
    name: DrMueller/ALMStuff
    ref: refs/heads/master
    endpoint: GitHub-DrMueller

jobs:
- job: 'BuildAndPublishToNuGet'
  displayName: 'Build and publish to NuGet'
  pool:
    vmImage: 'windows-2022'
  steps:
  - template: AzureDevOps/BuildTemplates/NetCore/Steps/Initialize_And_Test.yaml@ALMStuff
    parameters:
      BuildConfiguration: $(BuildConfiguration)
  - template: AzureDevOps/BuildTemplates/NetCore/Steps/Publish.yaml@ALMStuff
    parameters:
      BuildConfiguration: $(BuildConfiguration)
      FolderToPublish: $(FolderToPublish)
      PublishPath: $(PublishPath)
  - template: AzureDevOps/BuildTemplates/NetCore/Steps/Build_And_Push_Docker.yaml@ALMStuff
    parameters:
      ApplyDockerstack: $(ApplyDockerstack)
  - task: PublishBuildArtifacts@1
    displayName: 'Publish'
    inputs:
      PathtoPublish: 'Pipelines/Releasing'